### ISSUE TITLE
Failing to load with Anki-2.1.21beta1

### ISSUE THREAD

**Issue by Cupbox** [lovac42/PretzelLogic#5]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Pretzel Logic Retention Benchmarking':
Traceback (most recent call last):
  File "aqt\addons.py", line 205, in loadAddons
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1168065472\__init__.py", line 8, in <module>
    from .main import *
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1168065472\main.py", line 21, in <module>
    from .pretzel_logic import *
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1168065472\pretzel_logic.py", line 10, in <module>
    from anki.lang import getLang
ImportError: cannot import name 'getLang' from 'anki.lang' (C:\Program Files\Anki\anki\lang.pyc)

**Comment by lovac42** [comment]
Just updated.

**Comment by Cupbox** [comment]
Works perfect. Thank you.
